package com.swapper;
import inventoryswapper.*;
import java.io.File;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class Swapper extends javax.swing.JFrame {

    private final InventorySwapper sugarSwapper;
    private ArrayList<Mill> millList;
    /**
     * Creates new form NewJFrame
     */
    public Swapper() {
        sugarSwapper = new InventorySwapper();
        millList = new ArrayList<>();
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sourceMIllComboBox = new javax.swing.JComboBox();
        txtPcs = new javax.swing.JTextField();
        sourceClassComboBox = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        swapClassComboBox = new javax.swing.JComboBox<>();
        btnSelectFile = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        sourceLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFrom = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSwap = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblFromSum = new javax.swing.JLabel();
        lblToSum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("SWAPPING");
        jLabel1.setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("FROM");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("TO");

        sourceMIllComboBox.setModel(new DefaultComboBoxModel(millList.toArray()));
        sourceMIllComboBox.setToolTipText("Select Source Mill");
        sourceMIllComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sourceMIllComboBox.setEnabled(false);

        txtPcs.setToolTipText("Number of Bags to Swap");
        txtPcs.setEnabled(false);

        sourceClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        sourceClassComboBox.setToolTipText("Select Swapping Classification");
        sourceClassComboBox.setEnabled(false);

        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        btnSearch.setText("Search Combination");
        btnSearch.setEnabled(false);
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        swapClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        swapClassComboBox.setToolTipText("Select Swapping Classification");
        swapClassComboBox.setEnabled(false);

        btnSelectFile.setText("Select File");
        btnSelectFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSelectFileMouseClicked(evt);
            }
        });

        jLabel7.setText("Source File:");

        sourceLabel.setText("Select File");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sourceMIllComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(swapClassComboBox, 0, 125, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnSearch)
                        .addGap(48, 48, 48)
                        .addComponent(btnSelectFile))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sourceClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPcs, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sourceLabel)))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sourceMIllComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPcs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sourceClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(swapClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(sourceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearch)
                        .addComponent(btnSelectFile))
                    .addComponent(btnClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblFrom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MILL", "WEEK ENDING", "CLASS", "PCS", "SERIAL NO"
            }
        ));
        jScrollPane1.setViewportView(tblFrom);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mapping Results");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("FROM");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("TO");

        tblSwap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MILL", "WEEK ENDING", "CLASS", "PCS", "SERIAL NO"
            }
        ));
        jScrollPane2.setViewportView(tblSwap);

        jLabel8.setText("Sum");

        jLabel9.setText("Sum");

        lblFromSum.setText("0");

        lblToSum.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel8)
                        .addGap(64, 64, 64)
                        .addComponent(lblFromSum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel9)
                        .addGap(54, 54, 54)
                        .addComponent(lblToSum)
                        .addGap(300, 300, 300))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(lblFromSum)
                    .addComponent(lblToSum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        clearTable();
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        ArrayList<Mill> swapMills = new ArrayList<>();
        ArrayList<SugarClass> foundCombinations;
        if(!sourceClassComboBox.getSelectedItem().toString().equals(swapClassComboBox.getSelectedItem().toString())){    
            for(Mill mill: millList){
                if(!mill.getMillName().equals(((Mill)sourceMIllComboBox.getSelectedItem()).getMillName())){
                    swapMills.add(mill);
                }
            }
            BigDecimal swapAmount = new BigDecimal(txtPcs.getText());
            swapAmount = swapAmount.multiply(new BigDecimal(100));
            foundCombinations = sugarSwapper.checkSwapping((Mill)sourceMIllComboBox.getSelectedItem(), 
            swapMills,sourceClassComboBox.getSelectedItem().toString(),swapClassComboBox.getSelectedItem().toString(),swapAmount.intValue());
            if(foundCombinations.get(0).getSugarList().isEmpty()){
                clearTable();
                String message = "Sorry. No combinations with sum " + swapAmount.divide(new BigDecimal(100)) + " found.";
                if((!sugarSwapper.getLowerSuggestion().equals(new BigDecimal(0)))||(!sugarSwapper.getUpperSuggestion().equals(new BigDecimal(0)))){
                    message = message + "\n" + "Nearest possible total found are:\n";
                    if(!sugarSwapper.getLowerSuggestion().equals(new BigDecimal(0))){
                        message = message + "Lower: " + sugarSwapper.getLowerSuggestion().divide(new BigDecimal(100)) + "\n";
                    }
                    if(!sugarSwapper.getUpperSuggestion().equals(new BigDecimal(0))){
                        message = message + "Upper: " + sugarSwapper.getUpperSuggestion().divide(new BigDecimal(100)); 
                    }
                }
                        
                        
                        
                JOptionPane.showMessageDialog(this, message);
            }
            else{
                tblFrom.setModel(new javax.swing.table.DefaultTableModel(new String [] {
                    "MILL", "WEEK ENDING", "CLASS", "PCS", "SERIAL NUMBER"
                }, foundCombinations.get(0).getSugarList().size()));
                tblSwap.setModel(new javax.swing.table.DefaultTableModel(new String [] {
                        "MILL", "WEEK ENDING", "CLASS", "PCS", "SERIAL NUMBER"
                    }, foundCombinations.get(1).getSugarList().size()));
                int ctr = 0;
                BigDecimal bags;
                BigDecimal sum = new BigDecimal(0);
                DateFormat df = new SimpleDateFormat("MM/dd/yy");
                for(Sugar sugar: foundCombinations.get(0).getSugarList()){
                    tblFrom.setValueAt(sugar.getMill(),ctr,0);
                    tblFrom.setValueAt(df.format(sugar.getPriority()),ctr,1);
                    tblFrom.setValueAt(sugar.getSugarClass(),ctr,2);
                    bags = new BigDecimal(sugar.getBags());
                    bags = bags.divide(new BigDecimal(100));
                    tblFrom.setValueAt(bags.toString(),ctr,3);
                    tblFrom.setValueAt(sugar.getSerialNumber(), ctr, 4);
                    sum = sum.add(bags);
                    ctr++;
                }
                lblFromSum.setText(sum.toString());
                ctr = 0;
                sum = new BigDecimal(0);
                for(Sugar sugar: foundCombinations.get(1).getSugarList()){
                    tblSwap.setValueAt(sugar.getMill(),ctr,0);
                    tblSwap.setValueAt(df.format(sugar.getPriority()),ctr,1);
                    tblSwap.setValueAt(sugar.getSugarClass(),ctr,2);
                    bags = new BigDecimal(sugar.getBags());
                    bags = bags.setScale(2, RoundingMode.HALF_DOWN);
                    bags = bags.divide(new BigDecimal(100));
                    tblSwap.setValueAt(bags.toString(),ctr,3);
                    tblSwap.setValueAt(sugar.getSerialNumber(), ctr, 4);
                    sum = sum.add(bags);
                    ctr++;
                }
                lblToSum.setText(sum.toString());
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "WARNING! Swapping Classifications are the Same.");
        }
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnSelectFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectFileMouseClicked
        //Create a file chooser
        final JFileChooser fc = new JFileChooser();
        
        //In response to a button click:
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            sugarSwapper.initializeMills(file.getAbsolutePath());
            //sugarSwapper.initializeMills("C:\\Users\\Acer\\Documents\\data.xlsx");//for test purposes
            millList = sugarSwapper.getMillList();
            sourceMIllComboBox.setModel(new DefaultComboBoxModel(millList.toArray()));
            sourceLabel.setText(file.getName());
            sourceMIllComboBox.setEnabled(true);
            swapClassComboBox.setEnabled(true);
            sourceClassComboBox.setEnabled(true);
            txtPcs.setEnabled(true);
            btnSearch.setEnabled(true);
        } else {
            sourceMIllComboBox.setEnabled(false);
            swapClassComboBox.setEnabled(false);
            sourceClassComboBox.setEnabled(false);
            txtPcs.setEnabled(false);
            btnSearch.setEnabled(false);
        }
    }//GEN-LAST:event_btnSelectFileMouseClicked

    private void clearTable(){
        tblFrom.setModel(new javax.swing.table.DefaultTableModel(new String [] {
            "MILL", "WEEK ENDING", "CLASS", "PCS", "SERIAL NUMBER"
            }, 4));
        tblSwap.setModel(new javax.swing.table.DefaultTableModel(new String [] {
            "MILL", "WEEK ENDING", "CLASS", "PCS", "SERIAL NUMBER"
            }, 4));
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Swapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Swapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Swapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Swapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Swapper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelectFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFromSum;
    private javax.swing.JLabel lblToSum;
    private javax.swing.JComboBox<String> sourceClassComboBox;
    private javax.swing.JLabel sourceLabel;
    private javax.swing.JComboBox sourceMIllComboBox;
    private javax.swing.JComboBox<String> swapClassComboBox;
    private javax.swing.JTable tblFrom;
    private javax.swing.JTable tblSwap;
    private javax.swing.JTextField txtPcs;
    // End of variables declaration//GEN-END:variables
}
